// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240906142603_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.ToTable("bottles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Heineken",
                            Size = 330
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Bud",
                            Size = 330
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Fosters",
                            Size = 330
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Doom Bar",
                            Size = 330
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Fridge", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottleid");

                    b.HasKey("StudentId", "BottleId");

                    b.ToTable("fridge");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jimi.jagger@google.com",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 2,
                            Email = "barack.jagger@google.com",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kate.presley@something.com",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mick.hepburn@theworld.ca",
                            FirstName = "Mick",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 5,
                            Email = "kate.jagger@gov.us",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 6,
                            Email = "kate.obama@gov.ru",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 7,
                            Email = "oprah.winslet@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 8,
                            Email = "charles.hepburn@tesla.com",
                            FirstName = "Charles",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 9,
                            Email = "kate.hepburn@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 10,
                            Email = "audrey.middleton@nasa.org.us",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 11,
                            Email = "kate.jagger@gov.us",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 12,
                            Email = "audrey.windsor@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 13,
                            Email = "kate.presley@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 14,
                            Email = "jimi.presley@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mick.hendrix@tesla.com",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 16,
                            Email = "audrey.trump@gov.us",
                            FirstName = "Audrey",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 17,
                            Email = "audrey.presley@something.com",
                            FirstName = "Audrey",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 18,
                            Email = "charles.trump@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 19,
                            Email = "oprah.hepburn@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 20,
                            Email = "jimi.winfrey@something.com",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 21,
                            Email = "kate.winslet@something.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 22,
                            Email = "charles.winslet@nasa.org.us",
                            FirstName = "Charles",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 23,
                            Email = "jimi.presley@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 24,
                            Email = "kate.obama@gov.ru",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 25,
                            Email = "kate.middleton@google.com",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 26,
                            Email = "kate.presley@something.com",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 27,
                            Email = "audrey.obama@google.com",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 28,
                            Email = "audrey.obama@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 29,
                            Email = "jimi.presley@nasa.org.us",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 30,
                            Email = "elvis.jagger@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 31,
                            Email = "audrey.jagger@tesla.com",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 32,
                            Email = "elvis.winslet@gov.ru",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 33,
                            Email = "barack.presley@gov.us",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 34,
                            Email = "mick.winslet@gov.nl",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 35,
                            Email = "audrey.trump@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 36,
                            Email = "donald.jagger@nasa.org.us",
                            FirstName = "Donald",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 37,
                            Email = "audrey.trump@something.com",
                            FirstName = "Audrey",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 38,
                            Email = "donald.hepburn@gov.us",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 39,
                            Email = "mick.presley@google.com",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 40,
                            Email = "donald.windsor@gov.ru",
                            FirstName = "Donald",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 41,
                            Email = "charles.middleton@gov.ru",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 42,
                            Email = "elvis.trump@google.com",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 43,
                            Email = "audrey.jagger@gov.nl",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 44,
                            Email = "audrey.jagger@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 45,
                            Email = "donald.winslet@gov.us",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 46,
                            Email = "elvis.trump@something.com",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 47,
                            Email = "oprah.windsor@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 48,
                            Email = "barack.middleton@gov.us",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 49,
                            Email = "elvis.hendrix@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 50,
                            Email = "jimi.hendrix@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 51,
                            Email = "audrey.jagger@google.com",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 52,
                            Email = "kate.middleton@gov.gr",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 53,
                            Email = "elvis.middleton@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 54,
                            Email = "kate.middleton@gov.nl",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 55,
                            Email = "donald.winslet@gov.us",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 56,
                            Email = "elvis.winslet@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 57,
                            Email = "donald.windsor@gov.nl",
                            FirstName = "Donald",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 58,
                            Email = "charles.windsor@bbc.co.uk",
                            FirstName = "Charles",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 59,
                            Email = "mick.windsor@gov.us",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 60,
                            Email = "mick.presley@something.com",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 61,
                            Email = "oprah.winfrey@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 62,
                            Email = "elvis.winslet@google.com",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 63,
                            Email = "oprah.hepburn@gov.us",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 64,
                            Email = "elvis.presley@google.com",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 65,
                            Email = "jimi.presley@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 66,
                            Email = "oprah.hepburn@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 67,
                            Email = "donald.presley@tesla.com",
                            FirstName = "Donald",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 68,
                            Email = "donald.hepburn@google.com",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 69,
                            Email = "charles.trump@gov.gr",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 70,
                            Email = "oprah.trump@google.com",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 71,
                            Email = "kate.trump@gov.gr",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 72,
                            Email = "donald.winfrey@theworld.ca",
                            FirstName = "Donald",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 73,
                            Email = "charles.winfrey@something.com",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 74,
                            Email = "elvis.hepburn@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 75,
                            Email = "donald.hepburn@gov.nl",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 76,
                            Email = "kate.presley@theworld.ca",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 77,
                            Email = "jimi.jagger@tesla.com",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 78,
                            Email = "jimi.hendrix@tesla.com",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 79,
                            Email = "charles.trump@tesla.com",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 80,
                            Email = "jimi.hepburn@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 81,
                            Email = "kate.hepburn@gov.us",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 82,
                            Email = "barack.obama@theworld.ca",
                            FirstName = "Barack",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 83,
                            Email = "jimi.hendrix@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 84,
                            Email = "jimi.windsor@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 85,
                            Email = "barack.jagger@gov.nl",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 86,
                            Email = "mick.obama@gov.nl",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 87,
                            Email = "elvis.middleton@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 88,
                            Email = "donald.obama@nasa.org.us",
                            FirstName = "Donald",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 89,
                            Email = "oprah.windsor@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 90,
                            Email = "audrey.hendrix@something.com",
                            FirstName = "Audrey",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 91,
                            Email = "jimi.hendrix@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 92,
                            Email = "mick.windsor@something.com",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 93,
                            Email = "jimi.winslet@something.com",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 94,
                            Email = "charles.winslet@gov.gr",
                            FirstName = "Charles",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 95,
                            Email = "audrey.winfrey@tesla.com",
                            FirstName = "Audrey",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 96,
                            Email = "mick.obama@theworld.ca",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 97,
                            Email = "elvis.windsor@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 98,
                            Email = "elvis.windsor@something.com",
                            FirstName = "Elvis",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 99,
                            Email = "jimi.hepburn@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 100,
                            Email = "kate.winslet@gov.gr",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 101,
                            Email = "jimi.winslet@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 102,
                            Email = "charles.windsor@google.com",
                            FirstName = "Charles",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 103,
                            Email = "barack.hepburn@gov.gr",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 104,
                            Email = "donald.hepburn@bbc.co.uk",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 105,
                            Email = "elvis.trump@google.com",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 106,
                            Email = "barack.jagger@gov.ru",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 107,
                            Email = "kate.presley@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 108,
                            Email = "jimi.windsor@gov.us",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 109,
                            Email = "barack.winslet@something.com",
                            FirstName = "Barack",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 110,
                            Email = "audrey.winfrey@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 111,
                            Email = "donald.hendrix@google.com",
                            FirstName = "Donald",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 112,
                            Email = "audrey.presley@nasa.org.us",
                            FirstName = "Audrey",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 113,
                            Email = "oprah.presley@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 114,
                            Email = "kate.trump@google.com",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 115,
                            Email = "mick.winslet@something.com",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 116,
                            Email = "audrey.winfrey@gov.us",
                            FirstName = "Audrey",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 117,
                            Email = "jimi.winfrey@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 118,
                            Email = "kate.obama@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 119,
                            Email = "kate.winslet@tesla.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 120,
                            Email = "oprah.middleton@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 121,
                            Email = "kate.jagger@gov.us",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 122,
                            Email = "audrey.winslet@nasa.org.us",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 123,
                            Email = "charles.hendrix@gov.us",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 124,
                            Email = "oprah.trump@gov.nl",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 125,
                            Email = "kate.trump@something.com",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 126,
                            Email = "kate.jagger@gov.nl",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 127,
                            Email = "oprah.presley@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 128,
                            Email = "donald.presley@gov.nl",
                            FirstName = "Donald",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 129,
                            Email = "audrey.presley@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 130,
                            Email = "kate.windsor@google.com",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 131,
                            Email = "kate.jagger@gov.gr",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 132,
                            Email = "mick.jagger@gov.gr",
                            FirstName = "Mick",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 133,
                            Email = "kate.hepburn@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 134,
                            Email = "oprah.jagger@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 135,
                            Email = "oprah.windsor@gov.nl",
                            FirstName = "Oprah",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 136,
                            Email = "elvis.hendrix@theworld.ca",
                            FirstName = "Elvis",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 137,
                            Email = "barack.hendrix@gov.ru",
                            FirstName = "Barack",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 138,
                            Email = "charles.winslet@gov.ru",
                            FirstName = "Charles",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 139,
                            Email = "jimi.presley@something.com",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 140,
                            Email = "kate.jagger@google.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 141,
                            Email = "barack.presley@gov.nl",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 142,
                            Email = "oprah.winslet@nasa.org.us",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 143,
                            Email = "audrey.hepburn@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 144,
                            Email = "oprah.jagger@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 145,
                            Email = "barack.hepburn@tesla.com",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 146,
                            Email = "mick.hepburn@theworld.ca",
                            FirstName = "Mick",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 147,
                            Email = "elvis.jagger@google.com",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 148,
                            Email = "elvis.winfrey@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 149,
                            Email = "oprah.winslet@gov.nl",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 150,
                            Email = "audrey.windsor@google.com",
                            FirstName = "Audrey",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 151,
                            Email = "barack.windsor@theworld.ca",
                            FirstName = "Barack",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 152,
                            Email = "barack.presley@nasa.org.us",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 153,
                            Email = "barack.winfrey@bbc.co.uk",
                            FirstName = "Barack",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 154,
                            Email = "mick.presley@gov.nl",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 155,
                            Email = "barack.obama@gov.gr",
                            FirstName = "Barack",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 156,
                            Email = "jimi.winslet@gov.us",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 157,
                            Email = "barack.winfrey@gov.ru",
                            FirstName = "Barack",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 158,
                            Email = "oprah.jagger@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 159,
                            Email = "mick.winslet@something.com",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 160,
                            Email = "charles.presley@gov.ru",
                            FirstName = "Charles",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 161,
                            Email = "jimi.hepburn@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 162,
                            Email = "elvis.trump@google.com",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 163,
                            Email = "barack.middleton@nasa.org.us",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 164,
                            Email = "mick.hendrix@gov.us",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 165,
                            Email = "elvis.winfrey@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 166,
                            Email = "barack.winslet@bbc.co.uk",
                            FirstName = "Barack",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 167,
                            Email = "kate.windsor@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 168,
                            Email = "kate.middleton@gov.us",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 169,
                            Email = "mick.obama@tesla.com",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 170,
                            Email = "oprah.hendrix@theworld.ca",
                            FirstName = "Oprah",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 171,
                            Email = "donald.hepburn@nasa.org.us",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 172,
                            Email = "kate.trump@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 173,
                            Email = "charles.presley@gov.gr",
                            FirstName = "Charles",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 174,
                            Email = "jimi.winslet@tesla.com",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 175,
                            Email = "mick.windsor@gov.gr",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 176,
                            Email = "kate.windsor@gov.nl",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 177,
                            Email = "jimi.hendrix@something.com",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 178,
                            Email = "elvis.presley@google.com",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 179,
                            Email = "kate.hendrix@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 180,
                            Email = "barack.hepburn@gov.gr",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 181,
                            Email = "kate.jagger@tesla.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 182,
                            Email = "donald.middleton@tesla.com",
                            FirstName = "Donald",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 183,
                            Email = "barack.jagger@something.com",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 184,
                            Email = "charles.hendrix@gov.ru",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 185,
                            Email = "elvis.presley@bbc.co.uk",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 186,
                            Email = "jimi.windsor@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 187,
                            Email = "kate.presley@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 188,
                            Email = "barack.winfrey@theworld.ca",
                            FirstName = "Barack",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 189,
                            Email = "charles.obama@gov.nl",
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 190,
                            Email = "audrey.jagger@gov.us",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 191,
                            Email = "mick.presley@google.com",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 192,
                            Email = "audrey.hendrix@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 193,
                            Email = "audrey.obama@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 194,
                            Email = "charles.middleton@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 195,
                            Email = "kate.obama@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 196,
                            Email = "kate.middleton@theworld.ca",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 197,
                            Email = "charles.middleton@gov.us",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 198,
                            Email = "oprah.jagger@google.com",
                            FirstName = "Oprah",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 199,
                            Email = "charles.middleton@gov.ru",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 200,
                            Email = "audrey.jagger@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 201,
                            Email = "kate.hepburn@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 202,
                            Email = "kate.winslet@gov.us",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 203,
                            Email = "mick.trump@gov.gr",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 204,
                            Email = "oprah.middleton@gov.us",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 205,
                            Email = "donald.hepburn@gov.gr",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 206,
                            Email = "barack.obama@google.com",
                            FirstName = "Barack",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 207,
                            Email = "kate.winfrey@google.com",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 208,
                            Email = "kate.middleton@gov.us",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 209,
                            Email = "kate.jagger@something.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 210,
                            Email = "kate.obama@google.com",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 211,
                            Email = "mick.jagger@google.com",
                            FirstName = "Mick",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 212,
                            Email = "mick.windsor@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 213,
                            Email = "audrey.middleton@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 214,
                            Email = "oprah.winslet@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 215,
                            Email = "kate.presley@gov.gr",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 216,
                            Email = "elvis.winslet@bbc.co.uk",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 217,
                            Email = "audrey.presley@tesla.com",
                            FirstName = "Audrey",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 218,
                            Email = "kate.trump@gov.us",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 219,
                            Email = "charles.hendrix@gov.nl",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 220,
                            Email = "oprah.trump@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 221,
                            Email = "kate.presley@gov.nl",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 222,
                            Email = "donald.winfrey@nasa.org.us",
                            FirstName = "Donald",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 223,
                            Email = "kate.winslet@gov.nl",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 224,
                            Email = "mick.hendrix@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 225,
                            Email = "kate.presley@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 226,
                            Email = "elvis.winslet@something.com",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 227,
                            Email = "mick.trump@google.com",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 228,
                            Email = "kate.jagger@google.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 229,
                            Email = "elvis.hendrix@gov.nl",
                            FirstName = "Elvis",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 230,
                            Email = "elvis.presley@gov.ru",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 231,
                            Email = "donald.winslet@something.com",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 232,
                            Email = "elvis.presley@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 233,
                            Email = "mick.trump@nasa.org.us",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 234,
                            Email = "jimi.hepburn@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 235,
                            Email = "audrey.winslet@nasa.org.us",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 236,
                            Email = "mick.trump@tesla.com",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 237,
                            Email = "mick.winslet@gov.us",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 238,
                            Email = "elvis.middleton@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 239,
                            Email = "jimi.jagger@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 240,
                            Email = "mick.hepburn@gov.gr",
                            FirstName = "Mick",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 241,
                            Email = "barack.middleton@something.com",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 242,
                            Email = "barack.middleton@gov.nl",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 243,
                            Email = "oprah.middleton@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 244,
                            Email = "kate.hendrix@gov.us",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 245,
                            Email = "elvis.obama@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 246,
                            Email = "jimi.hendrix@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 247,
                            Email = "audrey.middleton@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 248,
                            Email = "oprah.winfrey@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 249,
                            Email = "jimi.presley@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
