using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace workshop.wwwapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "students",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_students", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "bottles",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    brand = table.Column<string>(type: "text", nullable: false),
                    size = table.Column<int>(type: "integer", nullable: false),
                    StudentId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_bottles", x => x.id);
                    table.ForeignKey(
                        name: "FK_bottles_students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "students",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "students",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 2, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 3, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 4, "barack.windsor@theworld.ca", "Barack", "Windsor" },
                    { 5, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 6, "charles.hendrix@google.com", "Charles", "Hendrix" },
                    { 7, "audrey.hendrix@tesla.com", "Audrey", "Hendrix" },
                    { 8, "donald.hendrix@theworld.ca", "Donald", "Hendrix" },
                    { 9, "donald.presley@google.com", "Donald", "Presley" },
                    { 10, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 11, "oprah.windsor@gov.us", "Oprah", "Windsor" },
                    { 12, "jimi.winslet@gov.us", "Jimi", "Winslet" },
                    { 13, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 14, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 15, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 16, "barack.jagger@theworld.ca", "Barack", "Jagger" },
                    { 17, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 18, "oprah.middleton@gov.gr", "Oprah", "Middleton" },
                    { 19, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 20, "mick.hepburn@bbc.co.uk", "Mick", "Hepburn" },
                    { 21, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 22, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 23, "barack.obama@google.com", "Barack", "Obama" },
                    { 24, "elvis.trump@tesla.com", "Elvis", "Trump" },
                    { 25, "barack.winfrey@gov.gr", "Barack", "Winfrey" },
                    { 26, "donald.winfrey@gov.nl", "Donald", "Winfrey" },
                    { 27, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 28, "audrey.jagger@gov.gr", "Audrey", "Jagger" },
                    { 29, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 30, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 31, "donald.hepburn@nasa.org.us", "Donald", "Hepburn" },
                    { 32, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 33, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 34, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 35, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 36, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 37, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 38, "oprah.hepburn@gov.us", "Oprah", "Hepburn" },
                    { 39, "donald.jagger@gov.nl", "Donald", "Jagger" },
                    { 40, "donald.presley@something.com", "Donald", "Presley" },
                    { 41, "mick.winfrey@google.com", "Mick", "Winfrey" },
                    { 42, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 43, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 44, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 45, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 46, "mick.obama@gov.us", "Mick", "Obama" },
                    { 47, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 48, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 49, "audrey.winslet@theworld.ca", "Audrey", "Winslet" },
                    { 50, "audrey.winslet@gov.gr", "Audrey", "Winslet" },
                    { 51, "donald.presley@something.com", "Donald", "Presley" },
                    { 52, "audrey.obama@gov.gr", "Audrey", "Obama" },
                    { 53, "oprah.winfrey@google.com", "Oprah", "Winfrey" },
                    { 54, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 55, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 56, "mick.hepburn@bbc.co.uk", "Mick", "Hepburn" },
                    { 57, "jimi.hepburn@gov.us", "Jimi", "Hepburn" },
                    { 58, "charles.obama@tesla.com", "Charles", "Obama" },
                    { 59, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 60, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 61, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 62, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 63, "kate.jagger@nasa.org.us", "Kate", "Jagger" },
                    { 64, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 65, "charles.presley@nasa.org.us", "Charles", "Presley" },
                    { 66, "audrey.presley@gov.us", "Audrey", "Presley" },
                    { 67, "audrey.trump@something.com", "Audrey", "Trump" },
                    { 68, "elvis.hendrix@gov.us", "Elvis", "Hendrix" },
                    { 69, "kate.obama@gov.nl", "Kate", "Obama" },
                    { 70, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 71, "elvis.jagger@gov.us", "Elvis", "Jagger" },
                    { 72, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 73, "audrey.hendrix@bbc.co.uk", "Audrey", "Hendrix" },
                    { 74, "oprah.winslet@gov.us", "Oprah", "Winslet" },
                    { 75, "kate.presley@google.com", "Kate", "Presley" },
                    { 76, "mick.winfrey@gov.nl", "Mick", "Winfrey" },
                    { 77, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 78, "donald.trump@bbc.co.uk", "Donald", "Trump" },
                    { 79, "jimi.winfrey@tesla.com", "Jimi", "Winfrey" },
                    { 80, "charles.middleton@tesla.com", "Charles", "Middleton" },
                    { 81, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 82, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 83, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 84, "oprah.windsor@gov.ru", "Oprah", "Windsor" },
                    { 85, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 86, "barack.obama@something.com", "Barack", "Obama" },
                    { 87, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 88, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 89, "charles.presley@gov.gr", "Charles", "Presley" },
                    { 90, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 91, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 92, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 93, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 94, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 95, "donald.obama@something.com", "Donald", "Obama" },
                    { 96, "donald.jagger@gov.ru", "Donald", "Jagger" },
                    { 97, "elvis.winslet@gov.us", "Elvis", "Winslet" },
                    { 98, "oprah.hepburn@tesla.com", "Oprah", "Hepburn" },
                    { 99, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 100, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 101, "barack.jagger@theworld.ca", "Barack", "Jagger" },
                    { 102, "elvis.jagger@nasa.org.us", "Elvis", "Jagger" },
                    { 103, "oprah.obama@bbc.co.uk", "Oprah", "Obama" },
                    { 104, "mick.winfrey@gov.gr", "Mick", "Winfrey" },
                    { 105, "elvis.winfrey@theworld.ca", "Elvis", "Winfrey" },
                    { 106, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 107, "charles.windsor@google.com", "Charles", "Windsor" },
                    { 108, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 109, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 110, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 111, "oprah.jagger@something.com", "Oprah", "Jagger" },
                    { 112, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 113, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 114, "elvis.jagger@google.com", "Elvis", "Jagger" },
                    { 115, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 116, "donald.obama@google.com", "Donald", "Obama" },
                    { 117, "donald.obama@gov.ru", "Donald", "Obama" },
                    { 118, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 119, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 120, "mick.presley@something.com", "Mick", "Presley" },
                    { 121, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 122, "donald.middleton@nasa.org.us", "Donald", "Middleton" },
                    { 123, "donald.hendrix@nasa.org.us", "Donald", "Hendrix" },
                    { 124, "donald.hendrix@gov.us", "Donald", "Hendrix" },
                    { 125, "oprah.windsor@nasa.org.us", "Oprah", "Windsor" },
                    { 126, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 127, "kate.trump@bbc.co.uk", "Kate", "Trump" },
                    { 128, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 129, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 130, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 131, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 132, "mick.presley@gov.ru", "Mick", "Presley" },
                    { 133, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 134, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 135, "audrey.trump@gov.nl", "Audrey", "Trump" },
                    { 136, "barack.hepburn@gov.gr", "Barack", "Hepburn" },
                    { 137, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 138, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 139, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 140, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 141, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 142, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 143, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 144, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 145, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 146, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 147, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 148, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 149, "kate.presley@gov.us", "Kate", "Presley" },
                    { 150, "jimi.hendrix@something.com", "Jimi", "Hendrix" },
                    { 151, "audrey.winslet@google.com", "Audrey", "Winslet" },
                    { 152, "mick.winslet@gov.gr", "Mick", "Winslet" },
                    { 153, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 154, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 155, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 156, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 157, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 158, "donald.presley@gov.us", "Donald", "Presley" },
                    { 159, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 160, "mick.presley@nasa.org.us", "Mick", "Presley" },
                    { 161, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 162, "elvis.trump@tesla.com", "Elvis", "Trump" },
                    { 163, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 164, "kate.presley@google.com", "Kate", "Presley" },
                    { 165, "oprah.winfrey@nasa.org.us", "Oprah", "Winfrey" },
                    { 166, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 167, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 168, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 169, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 170, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 171, "elvis.presley@gov.us", "Elvis", "Presley" },
                    { 172, "oprah.winfrey@nasa.org.us", "Oprah", "Winfrey" },
                    { 173, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 174, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 175, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 176, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 177, "kate.obama@google.com", "Kate", "Obama" },
                    { 178, "mick.trump@nasa.org.us", "Mick", "Trump" },
                    { 179, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 180, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 181, "mick.hendrix@nasa.org.us", "Mick", "Hendrix" },
                    { 182, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 183, "kate.obama@gov.nl", "Kate", "Obama" },
                    { 184, "jimi.windsor@nasa.org.us", "Jimi", "Windsor" },
                    { 185, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 186, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 187, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 188, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 189, "jimi.hepburn@nasa.org.us", "Jimi", "Hepburn" },
                    { 190, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 191, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 192, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 193, "mick.hepburn@gov.us", "Mick", "Hepburn" },
                    { 194, "barack.winslet@google.com", "Barack", "Winslet" },
                    { 195, "oprah.windsor@gov.us", "Oprah", "Windsor" },
                    { 196, "oprah.jagger@gov.nl", "Oprah", "Jagger" },
                    { 197, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 198, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 199, "barack.windsor@theworld.ca", "Barack", "Windsor" },
                    { 200, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 201, "barack.middleton@gov.gr", "Barack", "Middleton" },
                    { 202, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 203, "mick.jagger@nasa.org.us", "Mick", "Jagger" },
                    { 204, "jimi.trump@something.com", "Jimi", "Trump" },
                    { 205, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 206, "oprah.winslet@gov.us", "Oprah", "Winslet" },
                    { 207, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 208, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 209, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 210, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 211, "barack.presley@gov.us", "Barack", "Presley" },
                    { 212, "charles.trump@tesla.com", "Charles", "Trump" },
                    { 213, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 214, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 215, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 216, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 217, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 218, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 219, "mick.hendrix@gov.us", "Mick", "Hendrix" },
                    { 220, "mick.windsor@gov.us", "Mick", "Windsor" },
                    { 221, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 222, "donald.jagger@google.com", "Donald", "Jagger" },
                    { 223, "mick.jagger@gov.gr", "Mick", "Jagger" },
                    { 224, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 225, "jimi.hepburn@nasa.org.us", "Jimi", "Hepburn" },
                    { 226, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 227, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 228, "oprah.hendrix@something.com", "Oprah", "Hendrix" },
                    { 229, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 230, "mick.winfrey@something.com", "Mick", "Winfrey" },
                    { 231, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 232, "elvis.jagger@gov.nl", "Elvis", "Jagger" },
                    { 233, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 234, "charles.presley@google.com", "Charles", "Presley" },
                    { 235, "audrey.obama@gov.gr", "Audrey", "Obama" },
                    { 236, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 237, "barack.middleton@gov.us", "Barack", "Middleton" },
                    { 238, "charles.presley@something.com", "Charles", "Presley" },
                    { 239, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 240, "audrey.middleton@bbc.co.uk", "Audrey", "Middleton" },
                    { 241, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 242, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 243, "donald.presley@gov.us", "Donald", "Presley" },
                    { 244, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 245, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 246, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 247, "mick.windsor@something.com", "Mick", "Windsor" },
                    { 248, "barack.presley@gov.us", "Barack", "Presley" },
                    { 249, "audrey.middleton@google.com", "Audrey", "Middleton" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_bottles_StudentId",
                table: "bottles",
                column: "StudentId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "bottles");

            migrationBuilder.DropTable(
                name: "students");
        }
    }
}
